.TH "2flatpak" "15" "July 2020" "2flatpak" "2flatpak"
.
.SH "NAME"
\fB2flatpak\fR \- Generate flatpak manifests from other build systems.
.
.SH "SYNOPSIS"
\fB2flatpak\fR \fB\-\-version\fR
.
.br
\fB2flatpak\fR [\fB\-\-verbose\fR|\fB\-v\fR] [\fIoptions\fR] \.\.\.
.
.SH "DESCRIPTION"
2flatpak generates flatpak manifests from other build systems.
.
.SH "SEE ALSO"
2flatpak Homepage: \fIhttps://github.com/louib/2flatpak\fR
.
.P
\fBgit\fR(1), \fBgit\-log\fR(1)
.
.SH "AUTHORS"
louib
.
.P
.
.SH "BUGS"
See issues on GitHub \fIhttps://github\.com/louib/2flatpak/issues\fR
