.TH "panbuild" "17" "July 2020" "panbuild" "panbuild"
.
.SH "NAME"
\fBpanbuild\fR \- The universal build manifest converter.
.
.SH "SYNOPSIS"
\fBpanbuild\fR \fB\-\-version\fR
.
.br
\fBpanbuild\fR [\fB\-\-verbose\fR|\fB\-v\fR] [\fIoptions\fR] \.\.\.
.
.SH "DESCRIPTION"
panbuild converts build manifests from different build systems.
.
.SH "SEE ALSO"
panbuild Homepage: \fIhttps://github.com/louib/panbuild\fR
.
.P
\fBgit\fR(1), \fBgit\-log\fR(1)
.
.SH "AUTHORS"
louib
.
.P
.
.SH "BUGS"
See issues on GitHub \fIhttps://github\.com/louib/panbuild/issues\fR
