#!/usr/bin/env python3
import yaml
import json
import sys

if __name__ == '__main__':
    if len(sys.argv) < 1:
        print("Usage: yml2json com.domain.appName.yml")

    input_path = sys.argv[1]
    print(json.dumps(
        yaml.load(open(input_path, 'r')),
        indent=2
    ))
